# Generated by Django 5.2.1 on 2025-05-28 15:02

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zones', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archived', models.BooleanField(default=False)),
                ('x', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('y', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('side', models.CharField(choices=[('A', 'Side A'), ('B', 'Side B')], help_text='Which side (A or B) this position belongs to', max_length=1)),
                ('terrain', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='positions', to='zones.terrain')),
            ],
            options={
                'ordering': ['terrain', 'side', 'x', 'y'],
            },
        ),
    ]
