# Generated by Django 5.2.1 on 2025-05-22 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0002_alter_match_date_start'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='date_start',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='match',
            name='duration',
            field=models.DurationField(blank=True, null=True),
        ),
    ]
