# Generated by Django 5.2.1 on 2025-05-23 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0003_alter_match_date_start_alter_match_duration'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='match',
            name='winner',
        ),
        migrations.AlterField(
            model_name='match',
            name='visibility',
            field=models.CharField(choices=[('PUBLIC', 'Public'), ('PRIVATE', 'Private'), ('PUBLIC_TEAM', 'Public Team'), ('PRIVATE_TEAM', 'Private Team'), ('COMPETITION', 'Competition'), ('OTHER', 'Other')], default='PUBLIC', max_length=12),
        ),
        migrations.AlterField(
            model_name='teammembership',
            name='status',
            field=models.CharField(choices=[('INVITED', 'Invited'), ('MEMBER', 'Member'), ('DENIED', 'Denied'), ('ADMIN', 'Admin'), ('KICKED', 'Kicked'), ('LEFT', 'Left'), ('WINNER', 'Winner')], default='INVITED', max_length=10),
        ),
    ]
