# Generated by Django 5.2.1 on 2025-05-24 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0004_remove_match_winner_alter_match_visibility_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='max_participants',
            field=models.IntegerField(default=2),
        ),
        migrations.AddField(
            model_name='match',
            name='reward',
            field=models.IntegerField(default=0),
        ),
    ]
