# Generated by Django 5.2.1 on 2025-05-28 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0005_match_max_participants_match_reward'),
    ]

    operations = [
        migrations.AddField(
            model_name='matchmembership',
            name='side',
            field=models.IntegerField(default=0),
        ),
    ]
