# Generated by Django 5.2.1 on 2025-05-29 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0006_matchmembership_side'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='winnerside',
            field=models.IntegerField(default=1),
        ),
    ]
