# Generated by Django 5.2.1 on 2025-06-28 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0007_match_winnerside'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='rank',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Iron'), (2, 'Bronze'), (3, 'Silver'), (4, 'Gold'), (5, 'Platinum'), (6, 'Diamond')], default=1),
        ),
    ]
