# Generated by Django 5.2.1 on 2025-07-04 18:49

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0008_match_rank'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='cost',
            field=models.PositiveIntegerField(default=0, help_text='Cost of participating in the match (must be non-negative)', validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
