# Generated by Django 5.2.1 on 2025-08-19 16:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0010_remove_message_match_discussion_message_discussion'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='content',
            new_name='contentt',
        ),
    ]
