# Generated by Django 5.2.1 on 2025-08-19 16:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0011_rename_content_message_contentt'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='contentt',
            new_name='content',
        ),
    ]
