# Generated by Django 5.2.1 on 2025-08-19 17:18

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0012_rename_contentt_message_content'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='discussion',
            name='participants',
        ),
        migrations.AddField(
            model_name='discussion',
            name='group',
            field=models.ManyToManyField(blank=True, null=True, related_name='discussions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='discussion',
            name='type',
            field=models.CharField(choices=[('GROUP', 'Group'), ('MATCH', 'Match'), ('TEAM', 'Team')], max_length=10),
        ),
    ]
