# Generated by Django 5.2.1 on 2025-08-19 18:57

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0013_remove_discussion_participants_discussion_group_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='discussion',
            name='group',
            field=models.ManyToManyField(blank=True, related_name='discussions', to=settings.AUTH_USER_MODEL),
        ),
    ]
