# Generated by Django 5.2.1 on 2025-08-19 18:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0014_alter_discussion_group'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='content',
            new_name='ccontent',
        ),
    ]
