# Generated by Django 5.2.1 on 2025-08-19 18:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0015_rename_content_message_ccontent'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='ccontent',
            new_name='content',
        ),
    ]
