# Generated by Django 5.2.1 on 2025-08-19 20:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0016_rename_ccontent_message_content'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='discussion',
            new_name='discussion_id',
        ),
    ]
