# Generated by Django 5.2.1 on 2025-08-19 20:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0017_rename_discussion_message_discussion_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='discussion_id',
            new_name='discussion',
        ),
    ]
