# Generated by Django 5.2.1 on 2025-08-20 02:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0018_rename_discussion_id_message_discussion'),
    ]

    operations = [
        migrations.AddField(
            model_name='discussion',
            name='title',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
